// Showrun Design System — Style Dictionary v5 config
// Compiles W3C DTCG tokens in tokens/**/*.json to multiple output formats.
//
// Outputs (committed to build/):
//   - build/css/tokens.css           CSS custom properties for the LIGHT theme
//   - build/css/tokens-dark.css      CSS custom properties for the DARK theme
//   - build/json/tokens.json         Flat JSON for n8n / runtime consumption
//   - build/json/tokens-nested.json  Nested JSON preserving the source structure
//   - build/js/tokens.js             ES module exports for code-generated docs (DOCX/PPTX/PDF)
//   - build/tailwind/preset.js       Tailwind preset for the Astro site
//   - build/scss/_tokens.scss        SCSS variables (optional, web-team friendly)
//
// Run with: npm run build

import StyleDictionary from 'style-dictionary';
import { register } from '@tokens-studio/sd-transforms';

// Register Tokens Studio transforms (handles DTCG aliases, OKLCH, gradient compositions, etc.)
register(StyleDictionary);

// Custom transform: emit gradient tokens as CSS strings using the css-fallback extension
StyleDictionary.registerTransform({
  name: 'gradient/css',
  type: 'value',
  filter: (token) => token.$type === 'gradient' || token.type === 'gradient',
  transform: (token) => {
    const ext = token.$extensions || token.extensions || {};
    if (ext['showrun.css-fallback']) return ext['showrun.css-fallback'];
    // Fallback: build from stops
    const v = token.$value ?? token.value;
    if (!v || !v.stops) return '';
    const stops = v.stops.map(s => `${s.color} ${Math.round((s.position || 0) * 100)}%`).join(', ');
    return `linear-gradient(${v.angle || 'to right'}, ${stops})`;
  }
});

// Custom format: Tailwind preset
StyleDictionary.registerFormat({
  name: 'tailwind/preset',
  format: ({ dictionary }) => {
    const palette = {};
    const spacing = {};
    const radius = {};
    const fontFamily = {};
    const fontSize = {};
    const screens = {};

    const val = (t) => t.$value ?? t.value;

    dictionary.allTokens.forEach((t) => {
      // Skip retired colors — they're documented in tokens but excluded from Tailwind
      if (t.path[0] === 'color' && t.path[1] === 'retired') return;

      if (t.path[0] === 'color') {
        const key = t.path.slice(1).join('-');
        palette[key] = val(t);
      }
      if (t.path[0] === 'spacing') spacing[t.path.slice(1).join('-')] = val(t);
      if (t.path[0] === 'radius') radius[t.path.slice(1).join('-')] = val(t);
      if (t.path[0] === 'font' && t.path[1] === 'family') {
        const ext = t.$extensions || {};
        const stack = ext['showrun.fallback-stack'];
        fontFamily[t.path[2]] = stack
          ? stack.split(',').map(s => s.trim().replace(/^['\"]|['\"]$/g, ''))
          : [val(t)];
      }
      if (t.path[0] === 'font' && t.path[1] === 'size' && t.path[2] === 'screen') {
        fontSize[t.path.slice(3).join('-')] = val(t);
      }
      if (t.path[0] === 'breakpoint') screens[t.path[1]] = val(t);
    });

    return `// Auto-generated by Style Dictionary. Do not edit by hand.
// Source: tokens/**/*.json
// Built: ${new Date().toISOString()}

module.exports = {
  theme: {
    extend: {
      colors: ${JSON.stringify(palette, null, 2)},
      spacing: ${JSON.stringify(spacing, null, 2)},
      borderRadius: ${JSON.stringify(radius, null, 2)},
      fontFamily: ${JSON.stringify(fontFamily, null, 2)},
      fontSize: ${JSON.stringify(fontSize, null, 2)},
      screens: ${JSON.stringify(screens, null, 2)}
    }
  }
};
`;
  }
});

// Build configuration
const sd = new StyleDictionary({
  source: ['tokens/**/*.json'],
  preprocessors: ['tokens-studio'],

  platforms: {
    css: {
      transformGroup: 'css',
      transforms: ['name/kebab', 'gradient/css'],
      buildPath: 'build/css/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables',
          options: { outputReferences: true, selector: ':root' }
        }
      ]
    },

    'css-dark': {
      transformGroup: 'css',
      transforms: ['name/kebab', 'gradient/css'],
      buildPath: 'build/css/',
      files: [
        {
          destination: 'tokens-dark.css',
          format: 'css/variables',
          filter: (token) => token.path[0] === 'semantic-dark',
          options: { outputReferences: true, selector: '[data-theme=\"dark\"], .theme-dark' }
        }
      ]
    },

    scss: {
      transformGroup: 'scss',
      transforms: ['name/kebab', 'gradient/css'],
      buildPath: 'build/scss/',
      files: [
        { destination: '_tokens.scss', format: 'scss/variables' }
      ]
    },

    json: {
      transformGroup: 'js',
      buildPath: 'build/json/',
      files: [
        { destination: 'tokens.json', format: 'json/flat' },
        { destination: 'tokens-nested.json', format: 'json/nested' }
      ]
    },

    js: {
      transformGroup: 'js',
      buildPath: 'build/js/',
      files: [
        { destination: 'tokens.js', format: 'javascript/es6' },
        { destination: 'tokens.d.ts', format: 'typescript/es6-declarations' }
      ]
    },

    tailwind: {
      transformGroup: 'css',
      transforms: ['name/kebab', 'gradient/css'],
      buildPath: 'build/tailwind/',
      files: [
        { destination: 'preset.js', format: 'tailwind/preset' }
      ]
    }
  },

  log: {
    warnings: 'warn',
    verbosity: 'default',
    errors: { brokenReferences: 'console' }
  }
});

await sd.buildAllPlatforms();
console.log('\n✓ Showrun design tokens built. Outputs in build/.\n');
